-- 단가 데이터베이스 스키마 (11개 독립 테이블)
-- SQLite3 문법

-- 공통 컬럼 구조:
-- id (자동증가 기본키)
-- 품명 (TEXT, NOT NULL)
-- 규격 (TEXT)
-- 단위 (TEXT, NOT NULL)
-- 재료비 (REAL, DEFAULT 0)
-- 노묵비 (REAL, DEFAULT 0)
-- 경비 (REAL, DEFAULT 0)
-- 합계 (REAL, NOT NULL)
-- 비고 (TEXT)
-- 생성일시 (TIMESTAMP)
-- 수정일시 (TIMESTAMP)

-- 1. 일위대가 (설계 시 복합 공종 단가)
CREATE TABLE IF NOT EXISTS 일위대가 (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    품명 TEXT NOT NULL,
    규격 TEXT,
    단위 TEXT NOT NULL,
    재료비 REAL DEFAULT 0,
    노묵비 REAL DEFAULT 0,
    경비 REAL DEFAULT 0,
    합계 REAL NOT NULL,
    비고 TEXT,
    생성일시 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    수정일시 TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. 품셈단가 (품셈 기준 표준 단가)
CREATE TABLE IF NOT EXISTS 품셈단가 (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    품명 TEXT NOT NULL,
    규격 TEXT,
    단위 TEXT NOT NULL,
    재료비 REAL DEFAULT 0,
    노묵비 REAL DEFAULT 0,
    경비 REAL DEFAULT 0,
    합계 REAL NOT NULL,
    비고 TEXT,
    생성일시 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    수정일시 TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. 표준시장단가 (정부 고시 단가)
CREATE TABLE IF NOT EXISTS 표준시장단가 (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    품명 TEXT NOT NULL,
    규격 TEXT,
    단위 TEXT NOT NULL,
    재료비 REAL DEFAULT 0,
    노묵비 REAL DEFAULT 0,
    경비 REAL DEFAULT 0,
    합계 REAL NOT NULL,
    비고 TEXT,
    코드 TEXT,
    적용일자 DATE,
    노묵비율 REAL,
    생성일시 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    수정일시 TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 4. 견적단가 (특수 자재/공법 견적)
CREATE TABLE IF NOT EXISTS 견적단가 (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    품명 TEXT NOT NULL,
    규격 TEXT,
    단위 TEXT NOT NULL,
    재료비 REAL DEFAULT 0,
    노묵비 REAL DEFAULT 0,
    경비 REAL DEFAULT 0,
    합계 REAL NOT NULL,
    비고 TEXT,
    생성일시 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    수정일시 TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 5. 자재단가_사급 (시공사 조달 자재)
CREATE TABLE IF NOT EXISTS 자재단가_사급 (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    품명 TEXT NOT NULL,
    규격 TEXT,
    단위 TEXT NOT NULL,
    재료비 REAL DEFAULT 0,
    노묵비 REAL DEFAULT 0,
    경비 REAL DEFAULT 0,
    합계 REAL NOT NULL,
    비고 TEXT,
    생성일시 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    수정일시 TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 6. 자재단가_관급 (발주처 제공 자재)
CREATE TABLE IF NOT EXISTS 자재단가_관급 (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    품명 TEXT NOT NULL,
    규격 TEXT,
    단위 TEXT NOT NULL,
    재료비 REAL DEFAULT 0,
    노묵비 REAL DEFAULT 0,
    경비 REAL DEFAULT 0,
    합계 REAL NOT NULL,
    비고 TEXT,
    생성일시 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    수정일시 TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 7. 관급수수료 (관급 자재 관리비)
CREATE TABLE IF NOT EXISTS 관급수수료 (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    품명 TEXT NOT NULL,
    규격 TEXT,
    단위 TEXT NOT NULL,
    재료비 REAL DEFAULT 0,
    노묵비 REAL DEFAULT 0,
    경비 REAL DEFAULT 0,
    합계 REAL NOT NULL,
    비고 TEXT,
    생성일시 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    수정일시 TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 8. 관급울반비 (관급 자재 운송비)
CREATE TABLE IF NOT EXISTS 관급울반비 (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    품명 TEXT NOT NULL,
    규격 TEXT,
    단위 TEXT NOT NULL,
    재료비 REAL DEFAULT 0,
    노묵비 REAL DEFAULT 0,
    경비 REAL DEFAULT 0,
    합계 REAL NOT NULL,
    비고 TEXT,
    생성일시 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    수정일시 TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 9. 경비단가 (제경비 항목)
CREATE TABLE IF NOT EXISTS 경비단가 (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    품명 TEXT NOT NULL,
    규격 TEXT,
    단위 TEXT NOT NULL,
    재료비 REAL DEFAULT 0,
    노묵비 REAL DEFAULT 0,
    경비 REAL DEFAULT 0,
    합계 REAL NOT NULL,
    비고 TEXT,
    생성일시 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    수정일시 TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 10. 노임단가 (인걸비 기준)
CREATE TABLE IF NOT EXISTS 노임단가 (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    품명 TEXT NOT NULL,
    규격 TEXT,
    단위 TEXT NOT NULL,
    재료비 REAL DEFAULT 0,
    노묵비 REAL DEFAULT 0,
    경비 REAL DEFAULT 0,
    합계 REAL NOT NULL,
    비고 TEXT,
    생성일시 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    수정일시 TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 11. 실정보고단가 (실제 시공 단가, 감사 타겟)
CREATE TABLE IF NOT EXISTS 실정보고단가 (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    품명 TEXT NOT NULL,
    규격 TEXT,
    단위 TEXT NOT NULL,
    재료비 REAL DEFAULT 0,
    노묵비 REAL DEFAULT 0,
    경비 REAL DEFAULT 0,
    합계 REAL NOT NULL,
    비고 TEXT,
    설계단가_id INTEGER,
    차수 INTEGER,
    증감사유 TEXT,
    생성일시 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    수정일시 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (설계단가_id) REFERENCES 일위대가(id)
);

-- 인덱스 생성 (성능 최적화)
CREATE INDEX IF NOT EXISTS idx_일위대가_품명 ON 일위대가(품명);
CREATE INDEX IF NOT EXISTS idx_품셈단가_품명 ON 품셈단가(품명);
CREATE INDEX IF NOT EXISTS idx_표준시장단가_품명 ON 표준시장단가(품명);
CREATE INDEX IF NOT EXISTS idx_표준시장단가_코드 ON 표준시장단가(코드);
CREATE INDEX IF NOT EXISTS idx_견적단가_품명 ON 견적단가(품명);
CREATE INDEX IF NOT EXISTS idx_자재단가_사급_품명 ON 자재단가_사급(품명);
CREATE INDEX IF NOT EXISTS idx_자재단가_관급_품명 ON 자재단가_관급(품명);
CREATE INDEX IF NOT EXISTS idx_관급수수료_품명 ON 관급수수료(품명);
CREATE INDEX IF NOT EXISTS idx_관급울반비_품명 ON 관급울반비(품명);
CREATE INDEX IF NOT EXISTS idx_경비단가_품명 ON 경비단가(품명);
CREATE INDEX IF NOT EXISTS idx_노임단가_품명 ON 노임단가(품명);
CREATE INDEX IF NOT EXISTS idx_실정보고단가_품명 ON 실정보고단가(품명);
CREATE INDEX IF NOT EXISTS idx_실정보고단가_설계단가_id ON 실정보고단가(설계단가_id);
